# Generated by Django 5.2.8 on 2026-04-10 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('area_hectares', models.FloatField()),
                ('region', models.CharField(choices=[('Fergana', 'Fergana'), ('Tashkent', 'Tashkent'), ('Samarkand', 'Samarkand'), ('Bukhara', 'Bukhara'), ('Khorezm', 'Khorezm'), ('Karakalpakstan', 'Karakalpakstan'), ('Navoi', 'Navoi'), ('Andijan', 'Andijan'), ('Namangan', 'Namangan'), ('Kashkadarya', 'Kashkadarya'), ('Surkhandarya', 'Surkhandarya'), ('Jizzakh', 'Jizzakh'), ('Syrdarya', 'Syrdarya')], max_length=50)),
                ('crop_type', models.CharField(choices=[('cotton', 'Cotton'), ('wheat', 'Wheat'), ('corn', 'Corn'), ('vegetables', 'Vegetables'), ('rice', 'Rice'), ('other', 'Other')], max_length=20)),
                ('crop_growth_stage', models.CharField(choices=[('seedling', 'Seedling'), ('vegetative', 'Vegetative'), ('flowering', 'Flowering'), ('ripening', 'Ripening'), ('harvest', 'Harvest')], max_length=20)),
                ('soil_type', models.CharField(choices=[('sandy', 'Sandy'), ('loamy', 'Loamy'), ('clay', 'Clay'), ('silty', 'Silty')], max_length=20)),
                ('irrigation_system', models.CharField(choices=[('drip', 'Drip'), ('furrow', 'Furrow'), ('sprinkler', 'Sprinkler'), ('flood', 'Flood')], max_length=20)),
                ('water_source_pressure', models.CharField(choices=[('normal', 'Normal'), ('low', 'Low'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('latitude', models.FloatField(default=41.3)),
                ('longitude', models.FloatField(default=69.3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('satellite_ndvi', models.FloatField(default=0.5, help_text='NDVI 0.0–1.0')),
                ('satellite_evi', models.FloatField(default=0.4, help_text='EVI 0.0–1.0')),
                ('satellite_data_date', models.DateField(blank=True, null=True)),
                ('historical_avg_water_mm', models.FloatField(default=35.0)),
            ],
            options={
                'ordering': ['field_id'],
            },
        ),
        migrations.CreateModel(
            name='SoilSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moisture_percent', models.FloatField()),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('reading_time', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_sensors', to='fields.field')),
            ],
            options={
                'ordering': ['-reading_time'],
                'get_latest_by': 'reading_time',
            },
        ),
    ]
