# Generated by Django 5.2.8 on 2026-04-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='polygon_coords',
            field=models.JSONField(blank=True, help_text='List of [lat, lng] coordinates', null=True),
        ),
    ]
