# Generated by Django 5.2.8 on 2026-05-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_field_polygon_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='gee_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='gee_source',
            field=models.CharField(default='fallback', help_text='GEE | fallback', max_length=20),
        ),
        migrations.AddField(
            model_name='field',
            name='satellite_ndwi',
            field=models.FloatField(default=-0.1, help_text="NDWI -1.0–1.0 (suv ko'rsatkichi)"),
        ),
        migrations.AlterField(
            model_name='field',
            name='latitude',
            field=models.FloatField(default=42.4531),
        ),
        migrations.AlterField(
            model_name='field',
            name='longitude',
            field=models.FloatField(default=59.6104),
        ),
        migrations.AlterField(
            model_name='field',
            name='region',
            field=models.CharField(choices=[('Nukus', 'Nukus Tumani'), ('Karakalpakstan', "Qoraqalpog'iston"), ('Fergana', 'Fergana'), ('Tashkent', 'Tashkent'), ('Samarkand', 'Samarkand'), ('Bukhara', 'Bukhara'), ('Khorezm', 'Xorazm'), ('Navoi', 'Navoiy'), ('Andijan', 'Andijon'), ('Namangan', 'Namangan'), ('Kashkadarya', 'Qashqadaryo'), ('Surkhandarya', 'Surxondaryo'), ('Jizzakh', 'Jizzax'), ('Syrdarya', 'Sirdaryo')], max_length=50),
        ),
    ]
