# Generated by Django 5.2.8 on 2026-04-10 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature_max_c', models.FloatField()),
                ('temperature_min_c', models.FloatField()),
                ('humidity_percent', models.FloatField()),
                ('wind_speed_kmh', models.FloatField(default=10.0)),
                ('rainfall_mm', models.FloatField(default=0.0)),
                ('forecast_rain_3days_mm', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_records', to='fields.field')),
            ],
            options={
                'ordering': ['-date'],
                'get_latest_by': 'date',
                'unique_together': {('field', 'date')},
            },
        ),
    ]
