# Generated by Django 5.2.8 on 2026-04-10 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('recommendation_level', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('amount_mm', models.FloatField(default=0)),
                ('irrigate_today', models.BooleanField(default=False)),
                ('heatmap_value', models.FloatField(default=0.0)),
                ('recommendation_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='fields.field')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='IrrigationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount_mm', models.FloatField()),
                ('method', models.CharField(default='drip', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_records', to='fields.field')),
            ],
            options={
                'ordering': ['-date'],
                'get_latest_by': 'date',
            },
        ),
    ]
