# Generated by Django 5.2.8 on 2026-04-10 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('drought_risk', 'Drought Risk'), ('overwatering', 'Overwatering'), ('disease_risk', 'Disease Risk'), ('heat_stress', 'Heat Stress'), ('data_gap', 'Data Gap')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=10)),
                ('message', models.TextField()),
                ('action_required', models.BooleanField(default=False)),
                ('acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='fields.field')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('language', models.CharField(default='uz', max_length=5)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='fields.field')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
